// Auto-generated by Render build — do not edit manually.
// When running locally this file is served dynamically by the backend with an empty value,
// so the frontend auto-detects the backend from window.location.origin.
// On Render the build command overwrites this line with the production URL.
window.CLERK_API_BASE = window.CLERK_API_BASE || "";
